nx-admin:
    - CN=Firstname Lastname, OU=Unknown, O=Unknown, L=Anywhere, ST=CA, C=US
nx-deploy:
    - CN=Firstname Lastname, OU=Unknown, O=Unknown, L=Anywhere, ST=CA, C=US
    - CN=Firstname Lastname2, OU=Unknown, O=Unknown, L=Anywhere, ST=CA, C=US